name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install commitlint
        run: |
          npm install --global @commitlint/cli @commitlint/config-conventional

      - name: Copy commitlint config
        run: cp .commitlintrc.js $HOME/.commitlintrc.js

      - name: Validate PR commits
        run: npx commitlint --config $HOME/.commitlintrc.js --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
