name: Flake Check

on: [pull_request]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check Root Flake
        run: nix flake check

      - name: Check Template Flake
        run: |
          cd template
          nix flake check
          rm -f flake.lock
